### ISSUE TITLE
Noting Blobs in Queue

### ISSUE THREAD

**Issue by DeJayDevelopment** [BlobEmoji/queuebot#34]
Perhaps allowing the submitter to add "comments" or "notes" to an emote in queue would allow people who optimize blobs to note what they've changed and allow this to follow into the council queue and approval queue.

Inspiration:

![Inspiration Image](https://u.dejaydev.com/c2e3a.png)

**Comment by memethyl** [comment]
I'd guess that the simplest way to do this would be to match anything that **isn't** a blob emoji name in a submission, and put that in the VS post below the emotes themselves.

**Comment by TsundereBug** [comment]
You'd have to do some pattern matching to make sure you aren't getting junk data (some people submit with an existing emoji so it would catch an ID if just substringed or whatever)

I can do this, I just need to know if there is any preparation I need to keep in mind; database changes, etc.

**Comment by slice** [comment]
![image](https://user-images.githubusercontent.com/4206232/40033813-dd81623a-57ae-11e8-9e10-67eb8f4e2e96.png)
![image](https://user-images.githubusercontent.com/4206232/40033817-e0171d5a-57ae-11e8-9d73-bdba27123cf2.png)
![image](https://user-images.githubusercontent.com/4206232/40033821-e31a0e40-57ae-11e8-88e0-50ad69a50625.png)
![image](https://user-images.githubusercontent.com/4206232/40033822-e5bac0fe-57ae-11e8-9121-37206f6d6237.png)
![image](https://user-images.githubusercontent.com/4206232/40033826-ea0d08ce-57ae-11e8-986c-b4916bec4015.png)

Common pattern here in the suggestions channel right now. There's a message after ` - `.

**Comment by slice** [comment]
Also, how will this be displayed?

In the council queue? Approval queue? Both? What about during a :vs: vote?

**Comment by slice** [comment]
Unfinished implementation available @ https://github.com/BlobEmoji/queuebot/tree/suggestion-notes.

Currently, it detects notes any text after a dash and a space "- ".

For example, a message such as:

```
:blobcat: - Remastered HD, fixed overlaps and clipping.
```

would parse as expected. (`blobcat` being the name, `Remastered [...]` being the note).

Notes appear in `q!status` right now:

![image](https://user-images.githubusercontent.com/4206232/40153982-0f6bcd74-5941-11e8-8e5e-85f4dfd8153b.png)

I would add it to messages presented in the council queue but that would reduce the size of the emoji due to how the client functions, I'll just leave it in that state until we can come to a consensus.

**Comment by slice** [comment]
Merged as-is (9d4b64a017ef55b81a5166c44d2a1172f3456009).
